"""initial schema

Revision ID: d580da63086d
Revises: 
Create Date: 2026-06-08 19:45:58.428943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd580da63086d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_meta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('synced_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_meta_device_id', 'session_meta', ['device_id'], unique=False)
    op.create_index('ix_session_meta_updated_at', 'session_meta', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_meta_updated_at', table_name='session_meta')
    op.drop_index('ix_session_meta_device_id', table_name='session_meta')
    op.drop_table('session_meta')
    op.drop_table('devices')
    # ### end Alembic commands ###
